/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

DROP TABLE IF EXISTS `nvrpreferencia`;
CREATE TABLE `nvrpreferencia` (
  `nvrpref_id` int NOT NULL AUTO_INCREMENT,
  `dia` tinyint unsigned NOT NULL,
  `tiempo_inicio` time NOT NULL,
  `tiempo_final` time NOT NULL,
  `cmr_id` int NOT NULL,
  `activo` tinyint unsigned NOT NULL,
  PRIMARY KEY (`nvrpref_id`),
  KEY `cmr_id` (`cmr_id`),
  CONSTRAINT `nvrpreferencia_ibfk_1` FOREIGN KEY (`cmr_id`) REFERENCES `camara` (`cmr_id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- INSERT INTO `nvrpreferencia` (`nvrpref_id`, `dia`, `tiempo_inicio`, `tiempo_final`, `cmr_id`, `activo`) VALUES (1, 5, '08:00:00', '18:00:00', 3, 1);


/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;